# Generated by Django 5.0.1 on 2024-01-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=250)),
                ('company', models.CharField(max_length=150)),
                ('location', models.TextField()),
                ('date', models.DateTimeField()),
                ('description', models.TextField()),
                ('distance', models.PositiveIntegerField()),
                ('image', models.TextField()),
                ('genres', models.CharField()),
            ],
        ),
    ]
