# Generated by Django 5.0.1 on 2024-01-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='genres',
        ),
        migrations.AddField(
            model_name='event',
            name='genres',
            field=models.ManyToManyField(related_name='events', to='genres.genre'),
        ),
    ]
