# Generated by Django 5.0.1 on 2024-01-15 04:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_attend'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='owned',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='event',
            name='attend',
            field=models.ManyToManyField(null=True, related_name='events_attend', to=settings.AUTH_USER_MODEL),
        ),
    ]
