# Generated by Django 5.0.1 on 2024-01-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_rename_owned_event_owner_alter_event_attend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='location',
            new_name='address',
        ),
        migrations.AddField(
            model_name='event',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='long',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
