# Generated by Django 5.0.1 on 2024-01-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_date'),
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='genres',
            field=models.ManyToManyField(null=True, related_name='events', to='genres.genre'),
        ),
    ]
