# Generated by Django 5.0.1 on 2024-01-17 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_event_attend'),
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, related_name='events', to='genres.genre'),
        ),
    ]
