# Generated by Django 5.0.1 on 2024-01-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_remove_event_genres_event_genres'),
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='genres',
        ),
        migrations.AddField(
            model_name='event',
            name='genres',
            field=models.ManyToManyField(blank=True, null=True, related_name='events', to='genres.genre'),
        ),
    ]
